services:
  - type: web
    name: lumina
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate
    startCommand: gunicorn Lumina.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com,localhost,127.0.0.1
      - key: DEBUG
        value: false
      - key: DATABASE_URL
        fromDatabase:
          name: lumina-db
          property: connectionString

databases:
  - name: lumina-db
    databaseName: lumina
    user: lumina